# SPDX-License-Identifier: MIT

[Distribution]
Distribution=debian
Release=bookworm

[Build]
CacheDirectory=mkosi.cache
History=yes
ToolsTree=yes
Incremental=yes

[Output]
Format=disk
OutputDirectory=out
ImageId=neuroos

[Content]
Bootable=yes
Autologin=yes
SELinuxRelabel=no

# Wayland desktop (MVP)
Packages=
 systemd-sysv
 linux-image-amd64
 firmware-linux-free
 greetd
 tuigreet
 sway
 waybar
 wofi
 foot

# Audio + graphics basics
Packages=
 pipewire
 wireplumber

# Web/PWA runtime (MVP)
Packages=
 chromium

# Flatpak ecosystem (MVP)
Packages=
 flatpak
 xdg-desktop-portal
 xdg-desktop-portal-gtk
 xdg-desktop-portal-wlr

# Quality-of-life tools
Packages=
 ca-certificates
 curl
 dbus
 locales
 sudo
 vim

KernelCommandLine=
 systemd.log_ratelimit_kmsg=0
 printk.devkmsg=on

[Runtime]
RAM=3G

