set $mod Mod4

font pango:monospace 10

exec_always --no-startup-id waybar
exec --no-startup-id neuroos-home

bindsym $mod+d exec wofi --show drun
bindsym $mod+Return exec foot
bindsym $mod+Shift+q kill
bindsym $mod+Shift+e exec swaynag -t warning -m 'Exit session?' -b 'Exit' 'swaymsg exit'

